[2019-02-05 18:39:44,827] {models.py:1361} INFO - Dependencies all met for <TaskInstance: ricopili_serial.hang_out 2015-06-05T00:00:00+00:00 [queued]>
[2019-02-05 18:39:44,833] {models.py:1361} INFO - Dependencies all met for <TaskInstance: ricopili_serial.hang_out 2015-06-05T00:00:00+00:00 [queued]>
[2019-02-05 18:39:44,833] {models.py:1573} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 4
--------------------------------------------------------------------------------

[2019-02-05 18:39:44,839] {models.py:1595} INFO - Executing <Task(BashOperator): hang_out> on 2015-06-05T00:00:00+00:00
[2019-02-05 18:39:44,840] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run ricopili_serial hang_out 2015-06-05T00:00:00+00:00 --job_id 13 --raw -sd DAGS_FOLDER/airflow_serial.py --cfg_path /var/folders/7d/56pc9qp912l0kjvwnn2ds4sh0000gn/T/tmpppa6zlx0']
[2019-02-05 18:39:45,549] {base_task_runner.py:101} INFO - Job 13: Subtask hang_out [2019-02-05 18:39:45,548] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-05 18:39:45,705] {base_task_runner.py:101} INFO - Job 13: Subtask hang_out [2019-02-05 18:39:45,705] {models.py:271} INFO - Filling up the DagBag from /Users/vasa/Projects/ripkelab/cloud_ricopili/prototypes/airflow_serial/dags/airflow_serial.py
[2019-02-05 18:39:45,871] {base_task_runner.py:101} INFO - Job 13: Subtask hang_out [2019-02-05 18:39:45,870] {cli.py:484} INFO - Running <TaskInstance: ricopili_serial.hang_out 2015-06-05T00:00:00+00:00 [running]> on host Vassilys-MacBook-Pro.local
[2019-02-05 18:39:45,888] {bash_operator.py:74} INFO - Tmp dir root location: 
 /var/folders/7d/56pc9qp912l0kjvwnn2ds4sh0000gn/T
[2019-02-05 18:39:45,890] {bash_operator.py:87} INFO - Temporary script location: /var/folders/7d/56pc9qp912l0kjvwnn2ds4sh0000gn/T/airflowtmpuexe_9pr/hang_outs44l3jfp
[2019-02-05 18:39:45,890] {bash_operator.py:97} INFO - Running command: sleep 120
[2019-02-05 18:39:45,898] {bash_operator.py:106} INFO - Output:
[2019-02-05 18:41:45,908] {bash_operator.py:114} INFO - Command exited with return code 0
